node:
  name: "node-1"
  data_dir: "./node_data"

server:
  address: "127.0.0.1:9001"
  token: "110368ae724fe6c1a852b33c8cce38465fdc56b2c2d40ce70750219849d74156"
  tls: false
  insecure_skip_verify: true

eventfwd:
  listen: "127.0.0.1:9100"

session:
  cowrie_tty_dir: ""

log:
  level: "info"
